<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.28.3" />
    <PackageReference Include="Grpc.Tools" Version="2.67.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.0" />
    <PackageReference Include="RSocket.Core" Version="0.2.7" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\sapl_types.proto" GrpcServices="None" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sapl.Core\Sapl.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Sapl.Rsocket.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
