name: .NET Core Build pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore "sapl-csharp/Sapl.Csharp.sln"
    - name: Build
      run: dotnet build "sapl-csharp/Sapl.Csharp.sln"
    - name: Test
      run: dotnet test "sapl-csharp/Sapl.Csharp.sln" --filter "Integration!=PDPRequired" --no-build --verbosity normal

  publish-nuget:
    needs: build  # Dieser Job wartet auf den Abschluss des Build-Jobs
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

   
    - name: Restore NuGet packages
      run: dotnet restore "sapl-csharp/Sapl.Csharp.sln"
      
    - name: Build
      run: dotnet build -c Release "sapl-csharp/Sapl.Csharp.sln"
      
    - name: Pack and Publish NuGet Package
      run: |
        dotnet pack -c Release "sapl-csharp/Sapl.Csharp.sln" --no-build
        mv -Force sapl-csharp/**/*.nupkg nugetPackages/ || true  # Das Verzeichnis wird nur erstellt, wenn es nicht bereits existiert
    - name: Commit and Push NuGet Package
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add nugetPackages/*.nupkg
        git commit -m "Publish NuGet package via GitHub Actions"
        git push
