name: .NET Core Build pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore "sapl-csharp/Sapl.Csharp.sln"
    - name: Build
      run: dotnet build "sapl-csharp/Sapl.Csharp.sln"
    - name: Test
      run: dotnet test "sapl-csharp/Sapl.Csharp.sln" --filter "Integration!=PDPRequired" --no-build --verbosity normal 
